"""add_generated_endpoints_to_test_suite

Revision ID: 6524e82f7870
Revises: 
Create Date: 2025-12-14 17:56:23.864047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6524e82f7870'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_suites', sa.Column('generated_endpoints', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_suites', 'generated_endpoints')
    # ### end Alembic commands ###

